- job_name: *******
  metrics_path: /probe
  params:
    module: [http_2xx]
  file_sd_configs:
    - files:
        - "./prometheus/targets/*****.json"
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-proxy:9116
    - target_label: component
      replacement: "virtualization"
